wrem/usuarios/urls.py
from django.conf.urls import url

from usuarios import views

urlpatterns = [
    url(r'^validar_email/(?P<uidb64>\w+)/(?P<token>\w+)/$', views.validar_email, name='validar_email'),
]

wrem/wrem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_jwt import views as jwt_views

from rem import views

urlpatterns = [
    # Angular 2 Client App
    url(r'^$', views.index, name='index'),

    # Django Auth
    url(r'^password_reset/$', auth_views.password_reset, {
        'template_name': 'usuarios/password_reset_form.html',
        'email_template_name': 'usuarios/password_reset_email.html',
    }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {
        'template_name': 'usuarios/password_reset_done.html',
    }, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {
        'template_name': 'usuarios/password_reset_confirm.html',
    }, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {
        'template_name': 'usuarios/password_reset_complete.html',
    }, name='password_reset_complete'),

    # Django Admin
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^secret/', include(admin.site.urls)),

    # Rest Framework API Auth
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Rest Framework JWT Auth
    url(r'^api-token-auth/', jwt_views.obtain_jwt_token),
    url(r'^api-token-refresh/', jwt_views.refresh_jwt_token),
    url(r'^api-token-verify/', jwt_views.verify_jwt_token),

    # Views de Usuarios
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),

    # Views de API
    url(r'^api/', include('rem.api_urls')),
    url(r'^api/', include('usuarios.api_urls')),
] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += [
    # catch-all pattern for compatibility with the Angular routes. This must be last in the list.
    url(r'^(?P<path>.*)/$', views.index)
]

wrem/usuarios/models.py
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.conf import settings
from django.contrib.sites.models import Site
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext as _
from django.utils import timezone
from django.template.loader import get_template
from django.template import Context

from simple_email_confirmation.models import SimpleEmailConfirmationUserMixin

from comun import models as common_models


class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', False)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Usuario(SimpleEmailConfirmationUserMixin, AbstractBaseUser, PermissionsMixin):
    """
    A class implementing a fully featured User model with admin-compliant
    permissions.

    Email and password are required. Other fields are optional.
    """

    email = models.EmailField(
        _('Email Address'), unique=True,
        error_messages={
            'unique': _("A user with that email already exists."),
        }
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(
        _('Staff Status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.')
    )
    is_active = models.BooleanField(
        _('Active'), default=False,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.')
    )
    date_joined = models.DateTimeField(_('Date Joined'), default=timezone.now)

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'

    class Meta(object):
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        abstract = False

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
    full_name = property(get_full_name)

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def __str__(self):
        if self.get_full_name():
            return '{nombre}'.format(nombre=self.get_full_name())
        else:
            return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def belongs_to_group(self, group):
        """ Checks whether the user belongs to the group parameter or not"""
        return self.grupos.filter(pk=group.pk).exists()

    def is_admin_of_group(self, group):
        """ Checks whether the user admins the group parameter or not"""
        return self.grupos_admin.filter(pk=group.pk).exists()


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def send_email_confirmation(sender, instance=None, created=False, **kwargs):
    if created and not instance.is_superuser and not instance.is_active:
        mail_html = get_template('usuarios/email_confirmation.html')
        current_site = Site.objects.get_current()
        ctx = Context({
            'uidb64': urlsafe_base64_encode(force_bytes(instance.id)).decode(),
            'token': instance.confirmation_key,
            'protocol': settings.PROTOCOL,
            'domain': current_site.domain,
            'site_name': current_site.name
        })
        html_content = mail_html.render(ctx)

        instance.email_user('Confirmación de registro en WREM', html_content, fail_silently=False)


class Grupo(common_models.TimeStampedModel):
    nombre = models.CharField('nombre', max_length=500, blank=False, null=True)
    administrador = models.ForeignKey(
        'usuarios.Usuario', related_name='grupos_admin', verbose_name='administrador', blank=False, null=True,
        on_delete=models.SET_NULL
    )
    usuarios = models.ManyToManyField('usuarios.Usuario', verbose_name='usuarios', related_name='grupos', blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'usuarios_grupo'
        verbose_name = 'grupo'
        verbose_name_plural = 'grupos'

wrem/usuarios/views.py
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import get_object_or_404, redirect

from usuarios.models import Usuario


def validar_email(request, uidb64, token):
    usuario = get_object_or_404(Usuario, id=urlsafe_base64_decode(uidb64).decode())
    usuario.confirm_email(token)
    usuario.is_active = True
    usuario.save()
    return redirect('/login?activated=true')

wrem/usuarios/templates/usuarios/axes_lockout.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}IP bloqueada{% endblock %}
{% block content_title %}<h1>IP bloqueada</h1>{% endblock %}
{% block content %}
<p>Su IP ha sido baneada durante 15 minutos tras {{ failure_limit }} intentos de login incorrectos.</p>
{% endblock %}

wrem/usuarios/templates/usuarios/email_confirmation.html
{% autoescape off %}
Gracias por registrarse en {{ site_name }}.

Para finalizar el registro debe confirmar su email en el siguiente enlace:
{% block confirmation_link %}
{{ protocol }}://{{ domain }}{% url 'usuarios:validar_email' uidb64=uidb64 token=token %}
{% endblock %}

Reciba un cordial saludo de parte del equipo de {{ site_name }}.

{% endautoescape %}

wrem/usuarios/templates/usuarios/password_reset_complete.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WREM Password Reset</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'usuarios/css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"><img src="{% static 'usuarios/img/logoupo.gif' %}" alt=""></a>
            </div>
        </div>
    </nav>
    <div class="container">
        <p>Su contraseña ha sido restablecida con éxito. Ahora puede logarse.</p>

        <p><a href="/login">Login</a></p>
    </div>
</body>
</html>

wrem/usuarios/templates/usuarios/password_reset_confirm.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WREM Password Reset</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'usuarios/css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"><img src="{% static 'usuarios/img/logoupo.gif' %}" alt=""></a>
            </div>
        </div>
    </nav>
    <div class="container">
        {% if validlink %}
            <p>Introduzca su contraseña por duplicado para verificar que la ha escrito correctamente:</p>
            <form method="post">{% csrf_token %}
                {{ form.new_password1.errors }}
                <p class="aligned wide"><label for="id_new_password1">Nueva contraseña:&nbsp;</label>{{ form.new_password1 }}</p>
                {{ form.new_password2.errors }}
                <p class="aligned wide"><label for="id_new_password2">Confirme contraseña:&nbsp;</label>{{ form.new_password2 }}</p>
                <p><input type="submit" value="Cambiar mi contraseña"/></p>
            </form>
        {% else %}
            <p>El link de restablecimiento de contraseña es erróneo, seguramente porque ya ha sido usado. Realice otra peticion de restablecimiento.</p>
        {% endif %}
    </div>
</body>
</html>

wrem/usuarios/templates/usuarios/password_reset_done.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WREM Password Reset</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'usuarios/css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"><img src="{% static 'usuarios/img/logoupo.gif' %}" alt=""></a>
            </div>
        </div>
    </nav>
    <div class="container">
        <p>Le hemos enviado un email con las instrucciones para restablecer su contraseña. Si existe una cuenta con el email que introdujo, debería recibirlo en breve.</p>

        <p>En caso de no recibir el email, asegúrese que ha introducido correctamente el email con el que se registró y verifique la carpeta de spam.</p>
    </div>
</body>
</html>

wrem/usuarios/templates/usuarios/password_reset_email.html
{% autoescape off %}
Está recibiendo este email porque se ha solicitado una nueva contraseña para su cuenta de usuario en {{ site_name }}.

Puede realizar el cambio en el siguiente enlace:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Su usuario, en caso de que lo haya olvidado, es: {{ user.get_username }}

¡Gracias por usar {{ site_name }}!

Reciba un cordial saludo de parte del equipo de {{ site_name }}.

{% endautoescape %}

wrem/usuarios/templates/usuarios/password_reset_form.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WREM Password Reset</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'usuarios/css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"><img src="{% static 'usuarios/img/logoupo.gif' %}" alt=""></a>
            </div>
        </div>
    </nav>
    <div class="container">
        <p>¿Ha olvidado su contraseña? Introduzca su email aquí y le enviaremos instrucciones sobre cómo obtener una nueva.</p>
        <form method="post">{% csrf_token %}
            {{ form.email.errors }}
            <p><label for="id_email">Dirección de email:</label> {{ form.email }} <input type="submit" value="Restablecer mi contraseña" /></p>
        </form>
    </div>
</body>
</html>